### ISSUE TITLE
Connection Getting Closed

### ISSUE THREAD

**Issue by Vinayak006** [Imgkl/EventFlux#13]
After successfully establishing a connection using the EventFlux package, the connection gets unexpectedly disconnecting when new SSE event arrives. 

Environment:
- SSE package version: 1.6.7+1
- Operating System: Android
- Flutter version: 3.19.4

Additional Details:
- Relevant code snippets or configurations
void _connect() {
    _eventFlux.connect(
      EventFluxConnectionType.get,
      AppConst.API_BASE_URL + ApiEndPoints.SSE,
      autoReconnect: true,
      onConnectionClose: () {
        logger.e("[SSE] Connection closed");
      },
      onError: (final EventFluxException p0) {
        logger.e("[SSE] error\n\np0");
      },
      onSuccessCallback: (final EventFluxResponse? response) {
        if (response != null && response.stream != null) {
          st = response.stream!.listen((final EventFluxData event) {
            logger.i("EVENT: ${event.event}\n\nData: ${event.data}");
          });
        }
        logger.i(
          "[SSE]\n\nStatus: ${response?.status}\n\nErrorMsg: ${response?.errorMessage}\n\n",
        );
      },
    );
  }

**Comment by Imgkl** [comment]
Haha. No worries. If you face any issues with my package in the future, please do open an issue.

**Comment by sam-ayo** [comment]
> Sorry! My bad. Its a server issue for us.

Hi @Vinayak006, I'm running into a similar issue. What was the server issue you ran into?
