### ISSUE TITLE
onSuccessCallback should not be called unless 200 is returned

### ISSUE THREAD

**Issue by jangruenwaldt** [Imgkl/EventFlux#15]
You can test this by adding an invalid target URL.

In the current version, onSuccessCallback will be called, but immediately afterward the error handler is called.

Ideally, onSuccessCallback is only called if the connection is actually established. This would help me to reset e.g. the expontential back off attempt counter after the connection is established.

**Comment by jangruenwaldt** [comment]
https://github.com/Imgkl/EventFlux/pull/16 made a PR for this

**Comment by Imgkl** [comment]
Hey @jangruenwaldt,

Thanks for the contribution, it is merged to `main` and a new version of the EventFlux is out now.
