### ISSUE TITLE
Any particular reason to make EventFlux a singleton?

### ISSUE THREAD

**Issue by tamcy** [Imgkl/EventFlux#3]
Hello! I was trying to find a package to handle SSE connection with Dart. I first found [flutter_client_sse](https://pub.dev/packages/flutter_client_sse) first, tried it, and eventually discovered your package.

What I'd like to do is to open two connections and listen to SSE event streams from different hosts. This is simple in Javascript where one just needs to create two EventStream instances. But one thing common in `flutter_client_sse` and your package is that both implements the SSE client as a singleton which keeps a single HTTP connection and stream. This is even advertised as a feature in your package. Hence my question - is there any technical reason that EventFlux must be implemented as a singleton? Thanks in advance!

**Comment by Imgkl** [comment]
Hello @tamcy ,

You're spot on. While the singleton pattern brings several benefits, such as simplified state management and resource efficiency, it does indeed limit the ability to handle multiple SSE connections concurrently.

This is a valuable piece of feedback, and it's clear that supporting multiple connections could be beneficial for many use cases. I'm actively considering this for next release of EventFlux and will aim to include this enhancement going forward.

Thank you for your input, and please stay tuned for updates in the upcoming versions!

**Comment by Imgkl** [comment]
Hello @tamcy,

I'm excited to let you know that the feature you requested is now available in EventFlux version 1.5.0. Please refer to the updated README for guidance on how to use this new functionality.

Thank you for bringing this to our attention and contributing to the improvement of EventFlux. Your input is invaluable to the project.

Happy coding!
