### ISSUE TITLE
Cant start flutter project neither on android/ios

### ISSUE THREAD

**Issue by kristofradi** [Imgkl/EventFlux#8]
We got error:

Error (Xcode): ../../../../.pub-cache/hosted/pub.dev/fetch_api-1.0.3/lib/src/_js.dart:1:8: Error: Dart library 'dart:js' is not
available on this platform.

Could not build the application for the simulator.

Is it a well-known problem, or what could be the issue for it?
I tried to downgrade to 1.5 version before web support, but still got the issue.

**Comment by Imgkl** [comment]
I am working on fixing this. There'll be a fix rolling out in next 24hrs.

**Comment by Imgkl** [comment]
Update: I’m still ironing out the wrinkles to ensure a smooth experience across all platforms. It appears the dependency issue is a bit more complex than initially thought.

To ensure EventFlux remains robust everywhere else, I'm temporarily disabling web support. My apologies for the hiccup – I'm on it and plan to have web support to be rolled out again within a week.

Version 1.6.6 is out now. Tested and working fine on Android and iOS.
