### ISSUE TITLE
reconnect error

### ISSUE THREAD

**Issue by xiazhichao** [Imgkl/EventFlux#9]
An error will occur when reconnecting. It is recommended to add "await" in front of "_stop()". After the previous link is completely disconnected, then reconnect
await _stop()

**Comment by Imgkl** [comment]
Thanks for pointing this error. This has been fixed on the latest update. 🎉

**Comment by Imgkl** [comment]
A regression was found where `_stop()` was not being awaited when max reconnect attempts are exhausted in `_attemptReconnectIfNeeded()`. This has been fixed on the `pre-release` branch — all other call sites already awaited `_stop()` correctly.
